### ISSUE TITLE
Missing folder

### ISSUE THREAD

**Issue by SidrahKaleem** [knub/master-thesis#1]
Hy! there is a missing folder of result, I need a file "20_news.palmetto.tsv" foe coding part.

**Comment by knub** [comment]
Unfortunately, I don't have access to that file anymore.

**Comment by SidrahKaleem** [comment]
Hy! I need to run WELDA code, & it's not working. I need it urgently.
Can you help me? or suggest something? Because your code which is in Scala
is not running because of missing directories. Please help me out!
Thank you..
